security:
    encoders:
        App\Entity\User: bcrypt

    password_hashers:
        # Use native password hasher, which auto-selects and migrates the best
        # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: /api/login
                check_path: /api/login_check
            logout:
                path: /api/logout
    access_control:
        - { path: ^/api/v1, roles: ROLE_ADMIN }

