version: '3'

services:
  web:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www:rw
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - db
    networks:
      - behat-sf-5-course

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www:delegated
    networks:
      - behat-sf-5-course

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: sf_behat_password
      POSTGRES_DB: sf_behat_db
      POSTGRES_USER: sf_behat_user
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 15432:5432
    networks:
      - behat-sf-5-course

  wiremock:
    image: wiremock/wiremock
    restart: on-failure
    ports:
      - 28080:8080
    networks:
      - behat-sf-5-course

networks:
  behat-sf-5-course:
    driver: bridge
