version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www:delegated
    ports:
      - 18080:8000
    links:
      - database
    networks:
      - behat-sf-5-course
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: sf_behat_password
      POSTGRES_DB: sf_behat_db
      POSTGRES_USER: sf_behat_user
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 15432:5432
    networks:
      - behat-sf-5-course
  wiremock:
    image: wiremock/wiremock
    restart: on-failure
    ports:
      - 28080:8080
    networks:
      - behat-sf-5-course
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - behat-sf-5-course
  chrome:
    image: selenium/node-chrome
    links:
      - hub
    networks:
      - behat-sf-5-course

networks:
  behat-sf-5-course:
    driver: bridge
