version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www:delegated
    ports:
      - 8080:8000
    networks:
      - behat-sf-5-course
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-13}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
#      POSTGRES_USER: ${POSTGRES_USER:-symfony}
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
#    networks:
#      - behat-sf-5-course
####< doctrine/doctrine-bundle ###
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - behat-sf-5-course

  chrome:
    image: selenium/node-chrome
    links:
      - hub
    networks:
      - behat-sf-5-course

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  behat-sf-5-course:
    driver: bridge
