api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login

api_login_check:
    path: /api/login_check
    controller: App\Controller\SecurityController::loginCheck

api_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout


api_v1_order_create:
    path: /api/v1/order/create
    controller: App\Controller\OrderController::create

