services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\FeatureContext:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_hasher'
        public: true
